apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesson
  template:
    metadata:
      labels:
        app: lesson
    spec:
      containers:
      - image: okteto.dev/lesson:latest
        name: lesson
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b0c52a08-0974-4af6-9176-1caffb73c66c"
        - name: Vless_Path
          value: "/ussokv"
        - name: Vmess_UUID
          value: "b0c52a08-0974-4af6-9176-1caffb73c66c"
        - name: Vmess_Path
          value: "/yssokm"
        - name: Share_Path
          value: "/ssttok"
