apiVersion: v1
kind: Service
metadata:
  name: wumi
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "wumi"
    port: 8080
  selector:
    app: wumi
